### ISSUE TITLE
the text is in front of the map and the character

### ISSUE THREAD

**Issue by x0rld** [TheElectronWill/why-roguelike#1]
![image](https://user-images.githubusercontent.com/45242856/71606156-de0cd000-2b6e-11ea-9512-32a44a7644fd.png)
It's not really playable like that xD

**Comment by TheElectronWill** [comment]
You've started the server and the client in the same terminal, haven't you? 😄 
You need to open 2 terminals: one for the client and one for the server, they're supposed to be separate.
